import { User, Complaint, StaffMember, AuditLog, NotificationItem, SystemSettings, TimelineEvent } from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-student-1',
    username: 'rajesh_k',
    email: 'rajesh@hostel.edu',
    fullName: 'Rajesh Kumar',
    role: 'STUDENT',
    roomNumber: 'B-203',
    block: 'Block B',
    phoneNumber: '+91 98765 43210',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-student-2',
    username: 'sneha_p',
    email: 'sneha@hostel.edu',
    fullName: 'Sneha Patel',
    role: 'STUDENT',
    roomNumber: 'A-104',
    block: 'Block A',
    phoneNumber: '+91 98765 11223',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-office-1',
    username: 'office_admin',
    email: 'office@hostel.edu',
    fullName: 'Priya Sharma (Office Admin)',
    role: 'HOSTEL_OFFICE',
    phoneNumber: '+91 98765 88990',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-electrician-1',
    username: 'electrician_murugan',
    email: 'electrician@hostel.edu',
    fullName: 'Murugan E. (Lead Electrician)',
    role: 'ELECTRICIAN',
    phoneNumber: '+91 98450 12345',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-cleaner-1',
    username: 'cleaner_ramesh',
    email: 'cleaning@hostel.edu',
    fullName: 'Ramesh S. (Sanitation Officer)',
    role: 'CLEANING_WORKER',
    phoneNumber: '+91 98450 67890',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-master-1',
    username: 'mess_master',
    email: 'master@hostel.edu',
    fullName: 'Chef Suresh (Mess Master)',
    role: 'MASTER',
    phoneNumber: '+91 98450 54321',
    avatarUrl: 'https://images.unsplash.com/photo-1556157382-97eda2d62296?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-watchman-1',
    username: 'watchman_bahadur',
    email: 'watchman@hostel.edu',
    fullName: 'Bahadur Singh (Chief Guard)',
    role: 'WATCHMAN',
    phoneNumber: '+91 98450 99887',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-deputy-1',
    username: 'deputy_warden',
    email: 'deputy@hostel.edu',
    fullName: 'Dr. Ananya Sen (Deputy Warden)',
    role: 'DEPUTY_WARDEN',
    phoneNumber: '+91 98111 22334',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-warden-1',
    username: 'chief_warden',
    email: 'warden@hostel.edu',
    fullName: 'Prof. K. Venkatesh (Chief Warden)',
    role: 'WARDEN',
    phoneNumber: '+91 98111 99887',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=120&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_STAFF: StaffMember[] = [
  {
    id: 'usr-electrician-1',
    name: 'Murugan E.',
    role: 'ELECTRICIAN',
    categoryHandled: ['ELECTRICAL'],
    phone: '+91 98450 12345',
    activeJobsCount: 2,
    isAvailable: true,
  },
  {
    id: 'usr-cleaner-1',
    name: 'Ramesh S.',
    role: 'CLEANING_WORKER',
    categoryHandled: ['CLEANING_HYGIENE'],
    phone: '+91 98450 67890',
    activeJobsCount: 1,
    isAvailable: true,
  },
  {
    id: 'usr-master-1',
    name: 'Chef Suresh',
    role: 'MASTER',
    categoryHandled: ['FOOD_MESS'],
    phone: '+91 98450 54321',
    activeJobsCount: 1,
    isAvailable: true,
  },
  {
    id: 'usr-watchman-1',
    name: 'Bahadur Singh',
    role: 'WATCHMAN',
    categoryHandled: ['SECURITY'],
    phone: '+91 98450 99887',
    activeJobsCount: 1,
    isAvailable: true,
  },
  {
    id: 'usr-office-1',
    name: 'Priya Sharma (Office Staff)',
    role: 'HOSTEL_OFFICE',
    categoryHandled: ['ROOM_FURNITURE', 'WATER_PLUMBING', 'INTERNET', 'GENERAL'],
    phone: '+91 98765 88990',
    activeJobsCount: 2,
    isAvailable: true,
  },
];

const now = new Date();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 60 * 60 * 1000).toISOString();
const hoursFromNow = (h: number) => new Date(now.getTime() + h * 60 * 60 * 1000).toISOString();

export const INITIAL_COMPLAINTS: Complaint[] = [
  {
    id: 'cmp-1',
    code: 'CMP-1024',
    studentId: 'usr-student-1',
    studentName: 'Rajesh Kumar',
    roomNumber: 'B-203',
    block: 'Block B',
    category: 'ELECTRICAL',
    title: 'Ceiling fan regulator not working and sparking',
    description: 'The ceiling fan in Room B-203 stopped rotating. The speed regulator makes sparking sounds when turned.',
    priority: 'HIGH',
    status: 'ASSIGNED',
    assignedStaffId: 'usr-electrician-1',
    assignedStaffName: 'Murugan E.',
    assignedStaffRole: 'ELECTRICIAN',
    evidenceUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=500&auto=format&fit=crop&q=80',
    createdAt: hoursAgo(2),
    updatedAt: hoursAgo(1.5),
    slaDeadline: hoursFromNow(10),
    slaTotalMinutes: 720, // 12 hours SLA
    slaRemainingMinutes: 600,
    slaState: 'RUNNING',
    isEscalated: false,
    isRepeatedIssue: true, // Repeated in Room B-203
  },
  {
    id: 'cmp-2',
    code: 'CMP-1025',
    studentId: 'usr-student-2',
    studentName: 'Sneha Patel',
    roomNumber: 'A-104',
    block: 'Block A',
    category: 'WATER_PLUMBING',
    title: 'Severe pipeline leakage under bathroom sink',
    description: 'Water is gushing from the pipe under the bathroom sink since morning, flooding the entryway.',
    priority: 'EMERGENCY',
    status: 'SUBMITTED', // In Hostel Office Queue! Unassigned
    createdAt: hoursAgo(1),
    updatedAt: hoursAgo(1),
    slaDeadline: hoursFromNow(3),
    slaTotalMinutes: 240, // 4 hours SLA
    slaRemainingMinutes: 180,
    slaState: 'RUNNING',
    isEscalated: false,
    isRepeatedIssue: false,
  },
  {
    id: 'cmp-3',
    code: 'CMP-1026',
    studentId: 'usr-student-1',
    studentName: 'Rajesh Kumar',
    roomNumber: 'B-203',
    block: 'Block B',
    category: 'CLEANING_HYGIENE',
    title: 'Corridor garbage bin overflowing and bad odor',
    description: 'The 2nd floor corridor garbage has not been cleared for 2 days. Bad odor entering rooms.',
    priority: 'MEDIUM',
    status: 'IN_PROGRESS',
    assignedStaffId: 'usr-cleaner-1',
    assignedStaffName: 'Ramesh S.',
    assignedStaffRole: 'CLEANING_WORKER',
    createdAt: hoursAgo(8),
    updatedAt: hoursAgo(1),
    slaDeadline: hoursFromNow(16),
    slaTotalMinutes: 1440,
    slaRemainingMinutes: 960,
    slaState: 'RUNNING',
    isEscalated: false,
    staffNotes: 'Currently cleaning corridor 201-210. Will finish by 12:30 PM.',
  },
  {
    id: 'cmp-4',
    code: 'CMP-1027',
    studentId: 'usr-student-1',
    studentName: 'Rajesh Kumar',
    roomNumber: 'B-203',
    block: 'Block B',
    category: 'FOOD_MESS',
    title: 'Dinner rice half-cooked and cold in South Mess',
    description: 'Dinner served at South Mess counter 2 had uncooked rice and lukewarm dal.',
    priority: 'MEDIUM',
    status: 'RESOLUTION_PENDING', // Ready for student confirmation/reopen
    assignedStaffId: 'usr-master-1',
    assignedStaffName: 'Chef Suresh',
    assignedStaffRole: 'MASTER',
    createdAt: hoursAgo(14),
    updatedAt: hoursAgo(0.5),
    slaDeadline: hoursFromNow(10),
    slaTotalMinutes: 1440,
    slaRemainingMinutes: 600,
    slaState: 'RUNNING',
    isEscalated: false,
    staffNotes: 'Inspected kitchen steam boilers. Rice batch replenished and calibration updated with kitchen team.',
    completionProofUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'cmp-5',
    code: 'CMP-1028',
    studentId: 'usr-student-2',
    studentName: 'Sneha Patel',
    roomNumber: 'A-104',
    block: 'Block A',
    category: 'SECURITY',
    title: 'Block A rear exit security gate latch broken',
    description: 'The emergency latch on the rear entrance remains unlocked at night, posing safety hazard.',
    priority: 'EMERGENCY',
    status: 'ESCALATED', // SLA breached and escalated to Deputy Warden!
    assignedStaffId: 'usr-watchman-1',
    assignedStaffName: 'Bahadur Singh',
    assignedStaffRole: 'WATCHMAN',
    createdAt: hoursAgo(28),
    updatedAt: hoursAgo(2),
    slaDeadline: hoursAgo(4), // Breached 4 hours ago!
    slaTotalMinutes: 1440,
    slaRemainingMinutes: -240,
    slaState: 'BREACHED',
    isEscalated: true,
    escalationLevel: 'DEPUTY_WARDEN',
    escalationReason: 'SLA threshold (24h) breached without on-site resolution. Escalate to Deputy Warden for hardware procurement.',
    escalatedAt: hoursAgo(4),
  },
  {
    id: 'cmp-6',
    code: 'CMP-1029',
    studentId: 'usr-student-2',
    studentName: 'Sneha Patel',
    roomNumber: 'A-104',
    block: 'Block A',
    category: 'INTERNET',
    title: 'Wi-Fi Access Point offline in Block A 1st Floor',
    description: 'SSID "HostelNet-A-1F" is not broadcasting. Entire wing disconnected.',
    priority: 'HIGH',
    status: 'ACKNOWLEDGED',
    assignedStaffId: 'usr-office-1',
    assignedStaffName: 'Priya Sharma (Office Staff)',
    assignedStaffRole: 'HOSTEL_OFFICE',
    createdAt: hoursAgo(5),
    updatedAt: hoursAgo(3),
    slaDeadline: hoursFromNow(7),
    slaTotalMinutes: 720,
    slaRemainingMinutes: 420,
    slaState: 'RUNNING',
    isEscalated: false,
  },
  {
    id: 'cmp-0',
    code: 'CMP-1018',
    studentId: 'usr-student-1',
    studentName: 'Rajesh Kumar',
    roomNumber: 'B-203',
    block: 'Block B',
    category: 'ELECTRICAL',
    title: 'Tube light flickering in Room B-203',
    description: 'Tube light starter was damaged. Replaced starter and tube.',
    priority: 'LOW',
    status: 'CLOSED',
    assignedStaffId: 'usr-electrician-1',
    assignedStaffName: 'Murugan E.',
    assignedStaffRole: 'ELECTRICIAN',
    createdAt: hoursAgo(96),
    updatedAt: hoursAgo(72),
    slaDeadline: hoursAgo(72),
    slaTotalMinutes: 1440,
    slaRemainingMinutes: 0,
    slaState: 'MET',
    isEscalated: false,
  },
];

export const INITIAL_TIMELINE: Record<string, TimelineEvent[]> = {
  'cmp-1': [
    {
      id: 'tl-1',
      complaintId: 'cmp-1',
      action: 'COMPLAINT_CREATED',
      description: 'Complaint submitted by student Rajesh Kumar (Room B-203).',
      actorId: 'usr-student-1',
      actorName: 'Rajesh Kumar',
      actorRole: 'STUDENT',
      timestamp: hoursAgo(2),
    },
    {
      id: 'tl-2',
      complaintId: 'cmp-1',
      action: 'AUTOMATICALLY_ASSIGNED',
      description: 'Auto-routed to Electrician (Murugan E.) via Assignment Automation Rule [Category: ELECTRICAL].',
      actorId: 'system',
      actorName: 'System Engine',
      actorRole: 'HOSTEL_OFFICE',
      timestamp: hoursAgo(2),
    },
    {
      id: 'tl-3',
      complaintId: 'cmp-1',
      action: 'SLA_STARTED',
      description: '12-Hour SLA Clock initialized. Target resolution deadline set.',
      actorId: 'system',
      actorName: 'SLA Engine',
      actorRole: 'HOSTEL_OFFICE',
      timestamp: hoursAgo(2),
    },
  ],
  'cmp-4': [
    {
      id: 'tl-10',
      complaintId: 'cmp-4',
      action: 'COMPLAINT_CREATED',
      description: 'Mess grievance submitted.',
      actorId: 'usr-student-1',
      actorName: 'Rajesh Kumar',
      actorRole: 'STUDENT',
      timestamp: hoursAgo(14),
    },
    {
      id: 'tl-11',
      complaintId: 'cmp-4',
      action: 'ASSIGNED',
      description: 'Assigned to Chef Suresh (Mess Master).',
      actorId: 'system',
      actorName: 'System',
      actorRole: 'HOSTEL_OFFICE',
      timestamp: hoursAgo(14),
    },
    {
      id: 'tl-12',
      complaintId: 'cmp-4',
      action: 'WORK_STARTED',
      description: 'Kitchen inspection initiated by Master.',
      actorId: 'usr-master-1',
      actorName: 'Chef Suresh',
      actorRole: 'MASTER',
      timestamp: hoursAgo(8),
    },
    {
      id: 'tl-13',
      complaintId: 'cmp-4',
      action: 'RESOLUTION_PENDING',
      description: 'Marked as resolved with inspection proof. Awaiting student confirmation.',
      actorId: 'usr-master-1',
      actorName: 'Chef Suresh',
      actorRole: 'MASTER',
      timestamp: hoursAgo(0.5),
    },
  ],
  'cmp-5': [
    {
      id: 'tl-20',
      complaintId: 'cmp-5',
      action: 'COMPLAINT_CREATED',
      description: 'Security defect submitted by Sneha Patel.',
      actorId: 'usr-student-2',
      actorName: 'Sneha Patel',
      actorRole: 'STUDENT',
      timestamp: hoursAgo(28),
    },
    {
      id: 'tl-21',
      complaintId: 'cmp-5',
      action: 'ASSIGNED',
      description: 'Assigned to Bahadur Singh (Watchman).',
      actorId: 'system',
      actorName: 'System',
      actorRole: 'HOSTEL_OFFICE',
      timestamp: hoursAgo(28),
    },
    {
      id: 'tl-22',
      complaintId: 'cmp-5',
      action: 'SLA_BREACHED',
      description: 'SLA limit (24 hours) passed without resolution.',
      actorId: 'system',
      actorName: 'SLA Engine',
      actorRole: 'HOSTEL_OFFICE',
      timestamp: hoursAgo(4),
    },
    {
      id: 'tl-23',
      complaintId: 'cmp-5',
      action: 'ESCALATED',
      description: 'Escalation triggered. Case referred to Deputy Warden Dr. Ananya Sen.',
      actorId: 'system',
      actorName: 'Escalation Engine',
      actorRole: 'DEPUTY_WARDEN',
      timestamp: hoursAgo(4),
    },
  ],
};

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-1',
    actorName: 'Office Admin (Priya Sharma)',
    actorRole: 'HOSTEL_OFFICE',
    action: 'SETTINGS_CHANGED',
    entity: 'SYSTEM_SETTINGS',
    entityId: 'ASSIGNMENT_AUTOMATION_ENABLED',
    oldValue: 'OFF',
    newValue: 'ON',
    reason: 'Restored automatic category dispatch after morning staff check-in.',
    timestamp: hoursAgo(6),
  },
  {
    id: 'aud-2',
    actorName: 'System Engine',
    actorRole: 'HOSTEL_OFFICE',
    action: 'AUTO_ASSIGN',
    entity: 'COMPLAINT',
    entityId: 'CMP-1024',
    oldValue: 'UNASSIGNED',
    newValue: 'ELECTRICIAN (Murugan E.)',
    reason: 'Routing rule [ELECTRICAL -> ELECTRICIAN] executed.',
    timestamp: hoursAgo(2),
  },
  {
    id: 'aud-3',
    actorName: 'SLA Engine',
    actorRole: 'DEPUTY_WARDEN',
    action: 'ESCALATE',
    entity: 'COMPLAINT',
    entityId: 'CMP-1028',
    oldValue: 'ASSIGNED (Watchman)',
    newValue: 'ESCALATED (Deputy Warden)',
    reason: '24-hour SLA expired with no resolution reported.',
    timestamp: hoursAgo(4),
  },
];

export const INITIAL_SETTINGS: SystemSettings = {
  assignmentAutomationEnabled: true, // Automation ON by default
  updatedAt: hoursAgo(6),
  updatedBy: 'Priya Sharma (Office Admin)',
};

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    recipientId: 'usr-student-1',
    type: 'ASSIGNED',
    title: 'Staff Assigned to CMP-1024',
    message: 'Electrician Murugan E. has been assigned to your fan repair complaint.',
    complaintId: 'cmp-1',
    isRead: false,
    createdAt: hoursAgo(2),
  },
  {
    id: 'notif-2',
    recipientId: 'usr-student-1',
    type: 'RESOLUTION_PENDING',
    title: 'Action Required: Confirm Resolution on CMP-1027',
    message: 'Chef Suresh has marked the food issue as resolved. Please review and close or reopen.',
    complaintId: 'cmp-4',
    isRead: false,
    createdAt: hoursAgo(0.5),
  },
  {
    id: 'notif-3',
    recipientId: 'usr-electrician-1',
    type: 'ASSIGNED',
    title: 'New Electrical Job: CMP-1024',
    message: 'Room B-203 ceiling fan regulator replacement assigned to you.',
    complaintId: 'cmp-1',
    isRead: false,
    createdAt: hoursAgo(2),
  },
  {
    id: 'notif-4',
    recipientId: 'usr-deputy-1',
    type: 'ESCALATED',
    title: 'Urgent Escalation: CMP-1028',
    message: 'Security issue in Block A has breached SLA and requires Deputy Warden intervention.',
    complaintId: 'cmp-5',
    isRead: false,
    createdAt: hoursAgo(4),
  },
  {
    id: 'notif-5',
    recipientId: 'usr-office-1',
    type: 'COMPLAINT_CREATED',
    title: 'New Complaint Pending Assignment: CMP-1025',
    message: 'Plumbing leak in Room A-104 requires staff assignment.',
    complaintId: 'cmp-2',
    isRead: false,
    createdAt: hoursAgo(1),
  },
];
